/**
 * Expands the decision table into golden fixtures — R-12-02.
 *
 * Emits two versioned artifacts from the single table:
 *   - packages/rules/generated/golden.json      (consumed by Vitest vs evaluate)
 *   - supabase/tests/generated/golden_cases.sql (pgTAP vs redeem_ticket)
 *
 * Deterministic: CI runs this and fails if `git diff` is non-empty, so the
 * table and the fixtures cannot drift.
 *
 * One case per row today (each row's `when` as-is). TODO(F0-05 follow-up):
 * expand each row over the cartesian product of the inputs it does not pin,
 * using `evaluate()` itself as ground truth for the unpinned combinations,
 * to reach the plan's "≥60 golden cases" close criterion. The pgTAP side
 * additionally needs real ticket/device fixtures per case, which depends on
 * the schema landing in F1-01.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ROWS } from '../src/decision-table.js';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..', '..');

type GoldenCase = {
  id: string;
  inputs: Record<string, unknown>;
  expect: string;
  applies: string[];
  precedence: number;
};

function buildCases(): GoldenCase[] {
  // TODO(F0-05): expand each row over the cartesian product of the inputs it
  // does not pin. For now, one representative case per row.
  return ROWS.map((row) => ({
    id: row.id,
    inputs: { ...row.when },
    expect: row.expect,
    applies: [...row.applies],
    precedence: row.precedence,
  }));
}

function writeJson(cases: GoldenCase[]): void {
  const out = join(repoRoot, 'packages', 'rules', 'generated', 'golden.json');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, JSON.stringify({ version: 1, cases }, null, 2) + '\n');
}

function writeSql(cases: GoldenCase[]): void {
  const out = join(
    repoRoot,
    'supabase',
    'tests',
    'generated',
    'golden_cases.sql',
  );
  mkdirSync(dirname(out), { recursive: true });
  const dbCases = cases.filter((c) => c.applies.includes('db'));
  const lines = [
    '-- Generated by packages/rules/scripts/gen-golden.ts — do not edit.',
    '-- Run `pnpm gen:golden` to regenerate. CI fails on a non-empty diff.',
    'begin;',
  ];
  if (dbCases.length === 0) {
    lines.push(
      'select plan(1);',
      "select pass('no golden cases yet — F0-05 blocked on the §8 catalog');",
    );
  } else {
    lines.push(`select plan(${dbCases.length});`, '');
    for (const c of dbCases) {
      lines.push(`-- case ${c.id}: expect ${c.expect}`);
      // TODO(F0-05): seed the ticket for these inputs and assert redeem_ticket().
    }
  }
  lines.push('select * from finish();', 'rollback;', '');
  writeFileSync(out, lines.join('\n'));
}

const cases = buildCases();
writeJson(cases);
writeSql(cases);
console.log(`gen:golden — ${cases.length} case(s) written.`);
